services:
  mkdocs:
    image: python:3.10-slim
    container_name: mkdocs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sh -c "pip install mkdocs-material && mkdocs serve -a 0.0.0.0:8000"