site_name: FPGA Peripheral Board Documentation
theme:
  name: material
  features:
    - navigation.instant

  logo: assets/logos/purdue_logo.svg
  font:
    text: Roboto
    code: Robot Mono
  palette:
    - scheme: purdue-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: purdue-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
extra_css:
  - stylesheets/extra.css
remote_branch: gh-pages

markdown_extensions:
  - tables

nav:
  - Home: index.md
  - Datasheets:
    - Codec: datasheet1.md
  - About: about.md