site_name: FPGA Peripheral Board Documentation
theme:
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom

nav:
  - Home: index.md
  - About: about.md

extra_css:
  - stylesheets/extra.css